"""Language configuration used by the rule NLG layer.

The assistant always has an English fallback.  Native-language templates are
kept deliberately short because eligibility data collection should be clear
and unambiguous.
"""

SUPPORTED_NATIVE_LANGUAGES = {
    "English",
    "Tamil",
    "Hindi",
    "Telugu",
    "Kannada",
    "Malayalam",
    "Bengali",
    "Marathi",
    "Gujarati",
    "Punjabi",
    "Odia",
}

SUPPORTED_ROMANIZED_LANGUAGES = {
    "Tanglish",
    "Hinglish",
    "Teluglish",
    "Kanglish",
    "Manglish",
    "Benglish",
}

LANGUAGE_ALIASES = {
    "en": "English",
    "ta": "Tamil",
    "hi": "Hindi",
    "te": "Telugu",
    "kn": "Kannada",
    "ml": "Malayalam",
    "bn": "Bengali",
    "mr": "Marathi",
    "gu": "Gujarati",
    "pa": "Punjabi",
    "or": "Odia",
}

# NOTE: Existing English/Tamil/Tanglish/Hindi/Hinglish wording is preserved
# so the established v3.5/v3.6 regression tests remain stable.
LANGUAGE_QUESTION_TEMPLATES = {
    "English": {
        "age": "What is your age?",
        "gender": "What is your gender?",
        "state": "Which state do you live in?",
        "education": "What qualification did you complete (for example B.E./B.Tech, B.Sc, BCA, Diploma, M.Tech or MCA)?",
        "category": "What is your social category?",
        "business_type": "What type of business are you planning?",
        "sector": "What sector does your business belong to?",
        "income": "What is your annual income?",
        "project_cost": "What is the estimated project cost?",
    },
    "Tamil": {
        "age": "உங்கள் வயது என்ன?",
        "gender": "உங்கள் பாலினம் என்ன?",
        "state": "நீங்கள் எந்த மாநிலத்தில் வசிக்கிறீர்கள்?",
        "education": "உங்கள் கல்வித் தகுதி என்ன?",
        "category": "உங்கள் சமூகப் பிரிவு என்ன?",
        "business_type": "நீங்கள் எந்த வகையான தொழிலை தொடங்கப் போகிறீர்கள்?",
        "sector": "உங்கள் தொழில் எந்த துறையைச் சேர்ந்தது?",
        "income": "உங்கள் ஆண்டு வருமானம் எவ்வளவு?",
        "project_cost": "திட்டத்திற்கான மதிப்பிடப்பட்ட செலவு எவ்வளவு?",
    },
    "Tanglish": {
        "age": "Ungaloda vayasu enna?",
        "gender": "Ungaloda gender enna?",
        "state": "Neenga entha state-la irukeenga?",
        "education": "Ungaloda education level enna?",
        "category": "Ungaloda social category enna?",
        "business_type": "Neenga enna type business start panna poringa?",
        "sector": "Ungaloda business entha sector-la irukku?",
        "income": "Ungaloda annual income evlo?",
        "project_cost": "Project cost approximately evlo?",
    },
    "Hindi": {
        "age": "आपकी उम्र क्या है?",
        "gender": "आपका लिंग क्या है?",
        "state": "आप किस राज्य में रहते हैं?",
        "education": "आपकी शिक्षा का स्तर क्या है?",
        "category": "आपकी सामाजिक श्रेणी क्या है?",
        "business_type": "आप किस प्रकार का व्यवसाय शुरू करना चाहते हैं?",
        "sector": "आपका व्यवसाय किस क्षेत्र से संबंधित है?",
        "income": "आपकी वार्षिक आय कितनी है?",
        "project_cost": "परियोजना की अनुमानित लागत कितनी है?",
    },
    "Hinglish": {
        "age": "Aapki age kya hai?",
        "gender": "Aapka gender kya hai?",
        "state": "Aap kis state mein rehte hain?",
        "education": "Aapki education level kya hai?",
        "category": "Aapki social category kya hai?",
        "business_type": "Aap kis type ka business start karna chahte hain?",
        "sector": "Aapka business kis sector mein hai?",
        "income": "Aapki annual income kitni hai?",
        "project_cost": "Project cost approximately kitna hai?",
    },
    "Telugu": {
        "age": "మీ వయస్సు ఎంత?",
        "gender": "మీ లింగం ఏమిటి?",
        "state": "మీరు ఏ రాష్ట్రంలో నివసిస్తున్నారు?",
        "education": "మీ విద్యార్హత ఏమిటి?",
        "category": "మీ సామాజిక వర్గం ఏమిటి?",
        "business_type": "మీరు కొత్త వ్యాపారం ప్రారంభిస్తున్నారా లేదా ఇప్పటికే వ్యాపారం ఉందా?",
        "sector": "మీ వ్యాపారం ఏ రంగానికి చెందినది?",
        "income": "మీ వార్షిక ఆదాయం ఎంత?",
        "project_cost": "ప్రాజెక్ట్ అంచనా వ్యయం ఎంత?",
    },
    "Kannada": {
        "age": "ನಿಮ್ಮ ವಯಸ್ಸು ಎಷ್ಟು?",
        "gender": "ನಿಮ್ಮ ಲಿಂಗ ಯಾವುದು?",
        "state": "ನೀವು ಯಾವ ರಾಜ್ಯದಲ್ಲಿ ವಾಸಿಸುತ್ತೀರಿ?",
        "education": "ನಿಮ್ಮ ವಿದ್ಯಾರ್ಹತೆ ಏನು?",
        "category": "ನಿಮ್ಮ ಸಾಮಾಜಿಕ ವರ್ಗ ಯಾವುದು?",
        "business_type": "ನೀವು ಹೊಸ ವ್ಯವಹಾರ ಆರಂಭಿಸುತ್ತಿದ್ದೀರಾ ಅಥವಾ ಈಗಾಗಲೇ ವ್ಯವಹಾರ ಇದೆಯಾ?",
        "sector": "ನಿಮ್ಮ ವ್ಯವಹಾರ ಯಾವ ಕ್ಷೇತ್ರಕ್ಕೆ ಸೇರಿದೆ?",
        "income": "ನಿಮ್ಮ ವಾರ್ಷಿಕ ಆದಾಯ ಎಷ್ಟು?",
        "project_cost": "ಯೋಜನೆಯ ಅಂದಾಜು ವೆಚ್ಚ ಎಷ್ಟು?",
    },
    "Malayalam": {
        "age": "നിങ്ങളുടെ വയസ് എത്രയാണ്?",
        "gender": "നിങ്ങളുടെ ലിംഗം എന്താണ്?",
        "state": "നിങ്ങൾ ഏത് സംസ്ഥാനത്തിലാണ് താമസിക്കുന്നത്?",
        "education": "നിങ്ങളുടെ വിദ്യാഭ്യാസ യോഗ്യത എന്താണ്?",
        "category": "നിങ്ങളുടെ സാമൂഹിക വിഭാഗം ഏതാണ്?",
        "business_type": "നിങ്ങൾ പുതിയ ബിസിനസ് ആരംഭിക്കുകയാണോ, നിലവിലുള്ളതാണോ?",
        "sector": "നിങ്ങളുടെ ബിസിനസ് ഏത് മേഖലയിലാണ്?",
        "income": "നിങ്ങളുടെ വാർഷിക വരുമാനം എത്രയാണ്?",
        "project_cost": "പദ്ധതിയുടെ കണക്കാക്കിയ ചെലവ് എത്രയാണ്?",
    },
    "Bengali": {
        "age": "আপনার বয়স কত?",
        "gender": "আপনার লিঙ্গ কী?",
        "state": "আপনি কোন রাজ্যে থাকেন?",
        "education": "আপনার শিক্ষাগত যোগ্যতা কী?",
        "category": "আপনার সামাজিক শ্রেণি কী?",
        "business_type": "আপনি নতুন ব্যবসা শুরু করছেন নাকি ইতিমধ্যে ব্যবসা আছে?",
        "sector": "আপনার ব্যবসা কোন খাতের?",
        "income": "আপনার বার্ষিক আয় কত?",
        "project_cost": "প্রকল্পের আনুমানিক খরচ কত?",
    },
    "Marathi": {
        "age": "तुमचे वय किती आहे?",
        "gender": "तुमचे लिंग काय आहे?",
        "state": "तुम्ही कोणत्या राज्यात राहता?",
        "education": "तुमची शैक्षणिक पात्रता काय आहे?",
        "category": "तुमचा सामाजिक प्रवर्ग कोणता आहे?",
        "business_type": "तुम्ही नवीन व्यवसाय सुरू करत आहात की विद्यमान व्यवसाय आहे?",
        "sector": "तुमचा व्यवसाय कोणत्या क्षेत्रात आहे?",
        "income": "तुमचे वार्षिक उत्पन्न किती आहे?",
        "project_cost": "प्रकल्पाची अंदाजित किंमत किती आहे?",
    },
    "Gujarati": {
        "age": "તમારી ઉંમર કેટલી છે?",
        "gender": "તમારું લિંગ શું છે?",
        "state": "તમે કયા રાજ્યમાં રહો છો?",
        "education": "તમારી શૈક્ષણિક લાયકાત શું છે?",
        "category": "તમારો સામાજિક વર્ગ કયો છે?",
        "business_type": "તમે નવો વ્યવસાય શરૂ કરી રહ્યા છો કે પહેલેથી વ્યવસાય છે?",
        "sector": "તમારો વ્યવસાય કયા ક્ષેત્રમાં છે?",
        "income": "તમારી વાર્ષિક આવક કેટલી છે?",
        "project_cost": "પ્રોજેક્ટનો અંદાજિત ખર્ચ કેટલો છે?",
    },
    "Punjabi": {
        "age": "ਤੁਹਾਡੀ ਉਮਰ ਕਿੰਨੀ ਹੈ?",
        "gender": "ਤੁਹਾਡਾ ਲਿੰਗ ਕੀ ਹੈ?",
        "state": "ਤੁਸੀਂ ਕਿਹੜੇ ਰਾਜ ਵਿੱਚ ਰਹਿੰਦੇ ਹੋ?",
        "education": "ਤੁਹਾਡੀ ਸਿੱਖਿਆ ਯੋਗਤਾ ਕੀ ਹੈ?",
        "category": "ਤੁਹਾਡੀ ਸਮਾਜਿਕ ਸ਼੍ਰੇਣੀ ਕੀ ਹੈ?",
        "business_type": "ਤੁਸੀਂ ਨਵਾਂ ਕਾਰੋਬਾਰ ਸ਼ੁਰੂ ਕਰ ਰਹੇ ਹੋ ਜਾਂ ਪਹਿਲਾਂ ਤੋਂ ਕਾਰੋਬਾਰ ਹੈ?",
        "sector": "ਤੁਹਾਡਾ ਕਾਰੋਬਾਰ ਕਿਹੜੇ ਖੇਤਰ ਵਿੱਚ ਹੈ?",
        "income": "ਤੁਹਾਡੀ ਸਾਲਾਨਾ ਆਮਦਨ ਕਿੰਨੀ ਹੈ?",
        "project_cost": "ਪ੍ਰੋਜੈਕਟ ਦੀ ਅੰਦਾਜ਼ਨ ਲਾਗਤ ਕਿੰਨੀ ਹੈ?",
    },
    "Odia": {
        "age": "ଆପଣଙ୍କ ବୟସ କେତେ?",
        "gender": "ଆପଣଙ୍କ ଲିଙ୍ଗ କଣ?",
        "state": "ଆପଣ କେଉଁ ରାଜ୍ୟରେ ରହୁଛନ୍ତି?",
        "education": "ଆପଣଙ୍କ ଶିକ୍ଷାଗତ ଯୋଗ୍ୟତା କଣ?",
        "category": "ଆପଣଙ୍କ ସାମାଜିକ ବର୍ଗ କଣ?",
        "business_type": "ଆପଣ ନୂତନ ବ୍ୟବସାୟ ଆରମ୍ଭ କରୁଛନ୍ତି କି ପୂର୍ବରୁ ବ୍ୟବସାୟ ଅଛି?",
        "sector": "ଆପଣଙ୍କ ବ୍ୟବସାୟ କେଉଁ କ୍ଷେତ୍ରରେ?",
        "income": "ଆପଣଙ୍କ ବାର୍ଷିକ ଆୟ କେତେ?",
        "project_cost": "ପ୍ରକଳ୍ପର ଅନୁମାନିତ ଖର୍ଚ୍ଚ କେତେ?",
    },

}

COMPLETION_MESSAGES = {
    "English": "All required information has been collected.",
    "Tamil": "தேவையான அனைத்து தகவல்களும் சேகரிக்கப்பட்டுவிட்டன.",
    "Tanglish": "Thevaiyana ella information-um collect panniyachu.",
    "Hindi": "सभी आवश्यक जानकारी एकत्र कर ली गई है।",
    "Hinglish": "Saari required information collect ho gayi hai.",
    "Telugu": "అవసరమైన సమాచారం మొత్తం సేకరించబడింది.",
    "Kannada": "ಅಗತ್ಯ ಮಾಹಿತಿಯನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ.",
    "Malayalam": "ആവശ്യമായ എല്ലാ വിവരങ്ങളും ശേഖരിച്ചു.",
    "Bengali": "প্রয়োজনীয় সব তথ্য সংগ্রহ করা হয়েছে।",
    "Marathi": "सर्व आवश्यक माहिती गोळा झाली आहे.",
    "Gujarati": "બધી જરૂરી માહિતી એકત્ર થઈ ગઈ છે.",
    "Punjabi": "ਸਾਰੀ ਲੋੜੀਂਦੀ ਜਾਣਕਾਰੀ ਇਕੱਠੀ ਹੋ ਗਈ ਹੈ।",
    "Odia": "ସମସ୍ତ ଆବଶ୍ୟକ ସୂଚନା ସଂଗ୍ରହ ହୋଇଛି।",
}
